[book]
authors = ["THIR Unsafety Checker Members"]
language = "en"
multilingual = false
src = "."
title = "THIR Unsafety Checker Project Group"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/project-thir-unsafeck"
